services:
  database:
    image: postgres:17.2
    container_name: database
    restart: always
    shm_size: 1gb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@database:5432/postgres?schema=public
    command: >
      sh -c "sleep 5 && pnpm install --store ${PNPM_STORE} && pnpm store prune --store ${PNPM_STORE} && pnpm exec prisma generate && pnpm exec prisma migrate dev --name init && pnpm dev"